### ISSUE TITLE
Windows Advertising ID

### ISSUE THREAD

**Issue by LeJohnDuff** [adjust/windows_sdk#16]
Microsoft apparently released an advertising ID. Same as IDFA and GPS ADID. It's apparently going to be more and more common with the release of windows 8.1. So we should probably support that as well.
Here are the specs:
http://msdn.microsoft.com/en-us/library/windows/apps/windows.system.userprofile.advertisingmanager.aspx

**Comment by uerceg** [comment]
Done. https://github.com/adjust/windows_sdk/releases/tag/v4.0.0
