### ISSUE TITLE
Readme misleading

### ISSUE THREAD

**Issue by tg44** [adjust/windows_sdk#28]
There are some uppercase vs lowercase error in the readme for example Adjust.TrackEvent vs Adjust.trackEvent. If you try to copy-paste codes from the readme it will not build :(

Some addition info:
If your project is separated to a portable package with view-models and a wpf8 with the wpf views. you can only use this sdk on the wpf8 project, but the applogic will be in the portable package. That would be nice if the readme could advice [something like this](http://stackoverflow.com/a/19848595/2118749) out of the box.

**Comment by uerceg** [comment]
Hi @tg44 

And thanks for pointing this out. It's been a while since Windows SDK was updated, but latest update to it (v4.12.0) is coming soon and this will be fixed. Thank you for pointing this to us!

Will let you know in here once update is live.

Cheers.

**Comment by uerceg** [comment]
@tg44 

Readme has been updated to show proper method signatures.

Cheers.
