### ISSUE TITLE
Using AdjustSDK in a C++ project

### ISSUE THREAD

**Issue by mgrviper** [adjust/windows_sdk#30]
As of now AdjustSDK for WinRT/UWP is a C# class library and this prevents projects written in C++ from using it (This is not supported scenario for C# class libraries.) This barrier can be bypassed by converting AdjustSDK to Windows Runtime Component which is pretty straightforward if not trivial.
However Windows App Certification Kit (part of deploying on Windows Store) have longstanding bug that prevents tests to pass correctly if C++ projects references any managed projects or components and as of this month also prevents from deploying to Windows Store. 

Said bug in WACK: 
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/7241c382-4afb-4a70-b6aa-0c895d8236f8/

Would be nice to have AdjustSDK for WinRT/UWP as C++ Windows Runtime Component as it would be easy to use from any WinRT / UWP projects in any .net language (managed or not)

**Comment by nonelse** [comment]
Hi @mgrviper. Thanks for the feedback.

We actually already faced a bug like that when we tried to make a windows target for our Cordova SDK.
We stopped pursuing it when we saw it would take more time than we had available then.

Our priority now for the windows SDK now, is to update it to a similar level to our iOs and Android SDK. We will eventually need to make a C++ target when we start to expand our non-native platforms SDKs to support Windows.

In the meanwhile, if you have experience in having such a C++ project linking against a C# PCL library and know of sources that we can use, every bit helps :)

Cheers.

**Comment by mgrviper** [comment]
Hello there. Thank you for timely answer.
Actually it seems there are (very simple) way to explicitly activate .net native for C++ projects.
As per https://msdn.microsoft.com/en-us/library/mt148501.aspx
Just need to manually add (as GUI checkbox mentioned in (1) is missing for C++ projects)
`<UseDotNetNativeToolchain>true</UseDotNetNativeToolchain>`
to `<PropertyGroup>` of your release configuration.

Originally i was misled by (2) and the likes where Microsoft's support state that C++ projects needn't and can't activate .net native for its managed Windows Runtime Components.

(1) https://stackoverflow.com/questions/31981569/how-to-configure-net-native-in-visual-studio-2015
(2) https://social.msdn.microsoft.com/Forums/sqlserver/en-US/7241c382-4afb-4a70-b6aa-0c895d8236f8

As of using C# component library in C++ projects: currently it is not possible (at least for Windows Store apps). But AdjustSDK C# component library may be converted (via Visual Studio) to Windows Runtime Component and it would allow use from projects written in any language. 

Just change in project properties "Output type" from "Class library" to "Windows Runtime Component" and fix some minor compatibility issues (which prevents from building).

![image](https://user-images.githubusercontent.com/22609274/29200481-9aa6414e-7e90-11e7-9943-d0a3ec5ebe71.png)
